### ISSUE TITLE
Native host has exited

### ISSUE THREAD

**Issue by Wkee** [nE0sIghT/chrome-gnome-shell-mirror#50] opened 2017-03-16 16:59 UTC
Thanks for your reply, I am new to ubuntu and I download  GNOME-shell-integration from google extension web store. But when I visit the page it doesn't work for me and just remind me with tips  "Native host has exited". At first I installed extension "hidetopbar" from github by following this page [https://github.com/mlutfy/hidetopbar ](https://github.com/mlutfy/hidetopbar) without using the GNOME-shell-integration, maybe it caused the crash so I deleted all of the related files about "hidetopbar" in `~/.local/share/gnome-shell/extensions/`, but this error exits.

emm, I don't get the meaning of "Run Chrome from command line. Go to e.g.o. to get error" exactly, I run chrome-gnome-shell in terminal it shows nothing, and how to use "Go to e.g.o" to get the error? I am too fresh to know it. Thanks for your time.

**Comment by Wkee** [comment] 2017-03-16 17:41
** (gnome-shell:12494): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Gjs-Message: JS LOG: Failed to register AuthenticationAgent
Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered

(gnome-shell:12494): Gjs-WARNING **: JS ERROR: could not get remote objects for service org.gnome.SettingsDaemon.Smartcard path /org/gnome/SettingsDaemon/Smartcard: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Smartcard was not provided by any .service files
_proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:83

[Thread 0x7fffc3818700 (LWP 12515) exited]
[Thread 0x7fffd8ac6700 (LWP 12509) exited]
[New Thread 0x7fffd8ac6700 (LWP 12656)]
[Thread 0x7fffd8ac6700 (LWP 12656) exited]
[New Thread 0x7fffd8ac6700 (LWP 12776)]
[New Thread 0x7fffc3818700 (LWP 12777)]
[Thread 0x7fffd8ac6700 (LWP 12776) exited]
[New Thread 0x7fffd8ac6700 (LWP 12826)]
[Thread 0x7fffd8ac6700 (LWP 12826) exited]
[Thread 0x7fffc3818700 (LWP 12777) exited]



So weird that I make sure that I have uninstalled hidetopbar and remove all related files, but I use gdb `r --replace` it make effects again, but I am still confused where are the bugs.

**Comment by nE0sIghT** [comment] 2017-03-16 18:51
> emm, I don't get the meaning of "Run Chrome from command line. Go to e.g.o. to get error"

1. Open terminal
2. If you are using Chromium then type "chromium-browser". If you are using Google Chrome then type "google-chrome"
3. Go to https://extensions.gnome.org - so you will get your error message
4. Copy terminal output here

**Comment by Wkee** [comment] 2017-03-17 03:34
Thanks a lot for your tutorial but when running Chrome  from the terminal:

`google-chrome https://extensions.gnome.org`

the webpage is opened in a new window of the actual browser:

`Created new window in existing browser session.`

It just opened the e.g.o page in chrome without anything else tips in terminal.

> Go to https://extensions.gnome.org - so you will get your error message

So is the method wrong or I wonder where can I find the error message?

**Comment by nE0sIghT** [comment] 2017-03-17 03:35
> the webpage is opened in a new window of the actual browser

Close running browser before

**Comment by Wkee** [comment] 2017-03-17 03:44
> Close running browser before
Thanks a lot, it finally works!

Here is the error message:

~$ google-chrome https://extensions.gnome.org
[3187:3187:0317/114122.073467:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[3112:3112:0317/114122.519280:ERROR:background_mode_manager_aura.cc(13)] Not implemented reached in virtual void BackgroundModeManager::EnableLaunchOnStartup(bool)
[3399] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[3399] Exception: 'NoneType' object has no attribute 'unpack'
[3400] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[3400] Exception: 'NoneType' object has no attribute 'unpack'

**Comment by nE0sIghT** [comment] 2017-03-17 04:03
You do not have GNOME Shell installed or running, so you can not use GNOME Shell integration and GNOME Shell extensions.

In next version of integration you will get descriptive message instead of "Native host has exited".

This issue is duplicate of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/35

**Comment by Wkee** [comment] 2017-03-17 04:19
![image](https://cloud.githubusercontent.com/assets/22097520/24028676/dea8991c-0b0b-11e7-97e4-3a8ad2c9c4d6.png)

**Comment by Wkee** [comment] 2017-03-17 04:19
and run unity
`The program 'unity' is currently not installed. You can install it by typing:
sudo apt install unity
`

**Comment by Wkee** [comment] 2017-03-17 04:33
my background
![image](https://cloud.githubusercontent.com/assets/22097520/24028856/676fdef8-0b0d-11e7-85e7-77b9a77c11f7.png)

![image](https://cloud.githubusercontent.com/assets/22097520/24028937/ef81b7a8-0b0d-11e7-8fbe-f2b36a75ba78.png)

**Comment by nE0sIghT** [comment] 2017-03-17 04:37
> my background

It's Metacity (GNOME Flashback).
GNOME Shell integration is created for GNOME Shell

**Comment by Wkee** [comment] 2017-03-17 04:42
How can I change it to GNOME Shell? I cannot tell the difference between them.

**Comment by nE0sIghT** [comment] 2017-03-17 04:45
I can not tell you since I'm not an Ubuntu user.
In general you should tell your display manager to start GNOME Shell session instead of Metacity session.

Try to ask at Ubuntu-related resources - [Launchpad](https://bugs.launchpad.net/) or some Ubuntu forums.

**Comment by Wkee** [comment] 2017-03-17 05:08
hah, question solved after executing these commands!
```
sudo apt-get remove metacity
sudo apt-get remove --auto-remove metacity
sudo apt-get purge metacity
sudo apt-get purge --auto-remove metacity
```
All in all, thanks a lot for your patient help and detailed account!

**Comment by nE0sIghT** [comment] 2017-03-17 05:09
Glad to hear it works for you :-)

**Closed by nE0sIghT** 2017-03-17 05:09 UTC
