### ISSUE TITLE
Check for Updates Fail

### ISSUE THREAD

**Issue by madorian** [nE0sIghT/chrome-gnome-shell-mirror#8] opened 2016-08-09 09:18 UTC
The issue reference here, I see constantly also on gnome-3.18.5

https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep/reviews

Attached image
![skjermdump fra 2016-08-09 11-13-02](https://cloud.githubusercontent.com/assets/10106206/17511379/e1716c46-5e22-11e6-9972-1978452e485b.png)

**Comment by nE0sIghT** [comment] 2016-08-09 09:20
Hi,

Please enable option "Show information about network errors" at extension Options page - this will give you exact network cause.

**Comment by madorian** [comment] 2016-08-09 19:47
Nope;), doesn't give me anything more. See attached.
![skjermdump fra 2016-08-09 21-45-25](https://cloud.githubusercontent.com/assets/10106206/17531102/cebff808-5e7a-11e6-9eda-690b3efe761c.png)

**Comment by nE0sIghT** [comment] 2016-08-09 20:03
Update check never works for you or this error happens from time to time?

**Comment by madorian** [comment] 2016-08-09 20:12
This box pops up like 50 times per day, until I figured out you could disable updates;) I've only had it installed a week, though;)

**Comment by nE0sIghT** [comment] 2016-08-09 20:18
Also did you click "Retry" button after enabling "Show information about network errors" option?

**Comment by madorian** [comment] 2016-08-09 20:26
I'm on Ubuntu GNU/Linux 16.04. I installed the connector, hmm, I don't remember. I think I used Firefox. I will try to install it via github. I did try the "Retry" button after enabling. See attached video: 

https://drive.google.com/file/d/0BzFLpLGShxwdLTlrX3JpNlFPdlU/view?usp=sharing

**Comment by nE0sIghT** [comment] 2016-08-09 20:42
For Ubuntu easy way is use ppa:
```
sudo add-apt-repository ppa:ne0sight/chrome-gnome-shell
sudo apt-get update
sudo apt-get install chrome-gnome-shell
```

Also please check if https://extensions.gnome.org/ is working for you in Chrome.

**Comment by madorian** [comment] 2016-08-09 20:47
Hmm, I think maybe I did use that repository:

Leser pakkelister ... Ferdig
Skaper oversikt over avhengighetsforhold       
Leser tilstandsinformasjon ... Ferdig   
chrome-gnome-shell is already the newest version (6.2-0ubuntu1).
Følgende pakker ble automatisk installert og er ikke lenger påkrevet:
  linux-headers-4.4.0-31 linux-headers-4.4.0-31-generic linux-image-4.4.0-31-generic linux-image-extra-4.4.0-31-generic
Use 'sudo apt autoremove' to remove them.
0 oppgraderte, 0 nylig installerte, 0 å fjerne og 23 ikke oppgradert.

**Comment by madorian** [comment] 2016-08-09 20:47
Yeah, I did; I thought you meant the actual chrome plugin

**Comment by nE0sIghT** [comment] 2016-08-09 20:53
I will recheck Ubuntu 16.04 tomorrow

**Comment by nE0sIghT** [comment] 2016-08-11 18:16
I just checked chrome-gnome-shell under Ubuntu GNOME 16.04.1 Live DVD and found no problems with update check.

1. Please close all Chromium windows, run "chromium-browser > /tmp/chromium.log 2>/tmp/chromium.err" from terminal, click "Retry" button for "Update failed" notification.
Close all Chromium windows. And attach files /tmp/chromium.log and /tmp/chromium.err to this bug report.
2. Create new clean browser profile (Chromium Settings -> Add Person) and check if https://extensions.gnome.org and extensions update check is working for you in clean profile.

![Ubuntu GNOME 16.04.1](https://coldzone.ru/upload/chrome-gnome-shell/chrome-gnome-shell-ubuntu-16.04.1.png)

**Comment by nE0sIghT** [comment] 2016-08-20 21:15
If you still have this problem add requested information and reopen issue.

**Comment by yut23** [comment] 2016-09-12 02:48
I have reproduced this in Chromium under Arch Linux, with chrome-gnome-shell version 7 and the GNOME Shell integration extension installed by the same package. There was no notable output in the terminal log files (chromium.log and chromium.err), but the extension.html debug page was showing a request to extensions.gnome.org was returning a 500 internal server error.

I did some testing and found that the problem was with an invalid version value in the Dash to Dock extension (`"version": ""`) that was breaking something server-side. I have no idea how that got removed, as the version was correct when I installed it.

I reinstalled Dash to Dock and everything works fine now.

This is the specific URL that was returning a 500 error: https://extensions.gnome.org/update-info/?shell_version=3.20.4&installed={"dash-to-dock@micxgx.gmail.com":{"version":""}}. A request with a valid version (https://extensions.gnome.org/update-info/?shell_version=3.20.4&installed={"dash-to-dock@micxgx.gmail.com":{"version":0}}, for example), does work.

**Comment by nE0sIghT** [comment] 2016-09-12 04:49
Excelent finding!
I will work around this issue in next version

**Comment by nE0sIghT** [comment] 2016-09-24 09:16
Version 7.1 released with this issue fixed.
Thanks again

**Closed by nE0sIghT** 2016-09-24 09:16 UTC
Labels: bug

**Comment by madorian** [comment] 2016-10-02 23:07
Hi, again;)

Is this supposed to work with yakkety?

Now I'm only getting: 

Although GNOME Shell integration extension is running, native host connector is not detected. Refer <a href='https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation'>documentation</a> for instructions about installing connector.

..and yes, the extension is installed

Should I file a new bug for this?

**Comment by madorian** [comment] 2016-10-02 23:08
The error message displays every 2 seconds, btw

**Comment by nE0sIghT** [comment] 2016-10-03 04:19
> Is this supposed to work with yakkety?

Yes, it should.
Please post screenshot and console log from Chromium.

Also please note, that recently chrome-gnome-shell package [is landed to universe Ubuntu Yakkety repository](https://launchpad.net/ubuntu/+source/chrome-gnome-shell/7.1-1) from Debian so check if you have installed PPA package or Universe repository package.

> Should I file a new bug for this?

It would be better to talk in new issue.

**Comment by madorian** [comment] 2016-11-22 08:56
Well, now it doesn't display that exact error message, but it has been replaced with a new one that says: 

"An update for GNOME Shell extensions available" and then goes on to list all my gnome extensions that can be upgraded. This box pops up supernumerary times all day long.

**Comment by madorian** [comment] 2016-11-22 08:58
![utvalg_036](https://cloud.githubusercontent.com/assets/10106206/20517178/3611229a-b09a-11e6-9125-7cb5c3847549.png)

**Comment by nE0sIghT** [comment] 2016-11-22 09:07
That is how it should work. So you do not want to update extensions? Then switch off update check.

**Comment by madorian** [comment] 2016-11-22 09:10
Well, that's the funny thing; it is turned off, but it has no effect. 

Also, what is it checking?

Is it the update of the Chrome extension itself or is it updates of my gnome plugins? or both?
![utvalg_038](https://cloud.githubusercontent.com/assets/10106206/20517543/c8bd85ce-b09b-11e6-9283-bf7f823b77e2.png)

**Comment by nE0sIghT** [comment] 2016-11-22 10:32
After you turned off update check did you closed notification popup? Add then you received popup again?

> Also, what is it checking?

It's checking available updates for GNOME Shell extensions.

**Comment by madorian** [comment] 2016-11-23 17:20
Yes, I've closed it like 15 times since I turned off the update check.

**Comment by madorian** [comment] 2016-12-12 01:25
I had it disabled caused it bothered me like 70 times per day, but now it says it's installed by administrator and it cannot be disabled. 

I have to remove it totally using apt to get rid of those messages now?;)

**Comment by madorian** [comment] 2016-12-12 01:28
Also, why is this issue closed?

Who closed it and why can't I reopen it?

**Comment by nE0sIghT** [comment] 2016-12-12 10:22
> Also, why is this issue closed?

https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/18
