### ISSUE TITLE
Enabling synchronization causes random disabling of GNOME extensions

### ISSUE THREAD

**Issue by DavidGitta** [nE0sIghT/chrome-gnome-shell-mirror#45] opened 2017-03-12 17:49 UTC
This has already been reported on the Chrome Web Store (not by me). I can confirm the issue, but I never got "a warning notification about timeout of syncing".

![screenshot-chrome-web-store](https://cloud.githubusercontent.com/assets/24809481/23834245/607aa62c-0753-11e7-8dbc-48eeea3a18e9.png)

**Comment by nE0sIghT** [comment] 2017-03-12 19:09
What can you say about disabled extensions - are they always random? Are they system extensions?

**Comment by DavidGitta** [comment] 2017-03-13 11:35
It's affecting all extensions. Not at the same time, but it seems to be random. Sometimes only one gets disabled, some times three.

**Comment by nE0sIghT** [comment] 2017-03-13 11:44
How are you using your GNOME Shell devices - at same time, sequential or both?
Please list your extensions and tell me if some of them are system extensions.

**Comment by DavidGitta** [comment] 2017-03-13 13:23
Extensions in use:
alternate-tab@gnome-shell-extensions.gcampax.github.com <--System extension
dash-to-dock@micxgx.gmail.com
dynamic-panel-transparency@rockon999.github.io
dynamicTopBar@gnomeshell.feildel.fr
user-theme@gnome-shell-extensions.gcampax.github.com <--System extension

I only use one device. So sync is just for kind of backup for me.

**Comment by nE0sIghT** [comment] 2017-03-14 08:12
Do you using "sleep mode" with your device?

**Comment by DavidGitta** [comment] 2017-03-14 11:19
Yes I am.

**Comment by mattsch** [comment] 2017-03-14 12:13
This has been driving me crazy as well.  I'm getting it after a simple screen lock/timeout and wakeup as well.  My extensions:
refresh-wifi@kgshank.net                                                                                                                                                                                                                      
caffeine@patapon.info                                                                                                                                                                                                                         
alternate-tab@gnome-shell-extensions.gcampax.github.com                                                                                                                                                                                       
gravatar@jr.rlabs.io                                                                                                                                                                                                                          
netspeed@hedayaty.gmail.com                                                                                                                                                                                                                   
places-menu@gnome-shell-extensions.gcampax.github.com                                                                                                                                                                                         
drive-menu@gnome-shell-extensions.gcampax.github.com                                                                                                                                                                                          
suspend-button@laserb                                                                                                                                                                                                                         
TopIcons@phocean.net                                                                                                                                                                                                                          
GPaste@gnome-shell-extensions.gnome.org - System                                                                                                                                                                                                       
auto-move-windows@gnome-shell-extensions.gcampax.github.com

**Comment by DavidGitta** [comment] 2017-03-14 12:22
@mattsch If you disable syncing, it will work normal for now.

**Comment by nE0sIghT** [comment] 2017-03-19 09:23
This is fixed in master.
It would be helpfull if someone will test changes.

**Comment by ebola-dc** [comment] 2017-03-21 08:32
Hello!

I'm tryed to install the unpacked version of this extension directly downloaded from GitHub to test it but I get this error message: '**Value 'key' is missing or invalid.**'

Could you please navigate me on the most easier install process?

Thanks a lot in advance!

**Comment by ebola-dc** [comment] 2017-03-21 08:45
OK! Seems I got it but everything is clear yet:( I'm testing it.

**Comment by ebola-dc** [comment] 2017-03-21 09:15
OK!

After the second try of installing it from source I think was successfully done. Before everything I simply unistalled the 'stock' extension from Chrome. First time I tried to use directly the extension folder as unpacked extension but after a 'key' error message I tried to follow strictly what are in the Wiki. Seemed that the installation was succesfully done as I got back the extension with 8.2 version but installed as enterprise policy.

The problem is that after 3 brute force test I got back the error. I tried to send my device to standby and get back. Between the secont trial I simply made my job then tried again to send into standby. Later I again waked it up. Until this point there was everything OK. And after some minutes I tried to send my device again to standby and after the wak I got the error again. 2-3 of my extensions was disabled again.

Just one information about the environment. My Chrome runs always in the background as I use some of such extensions or web applications.

Sorry to said my test results:(

**Comment by nE0sIghT** [comment] 2017-03-21 10:13
@ebola-dc 

1. Remove chrome-gnome-shell policy files from ```/etc/{chromium,opt/chrome}/policies/managed/``` and uninstall GNOME Shell integration browser extension installed from Chrome store, but keep distro's chrome-gnome-shell package.
2. Install coreutils, jq, 7z (p7zip) system packages.
3. Download latest chrome-gnome-shell git master sources.
4. From the sources root create ```build``` directory and cd to it.
5. Run ```cmake -DBUILD_CONNECTOR=OFF ../ && make```
6. Load extension in browser from ```build/extension/chrome``` directory

**Comment by ebola-dc** [comment] 2017-03-21 11:12
Hmmm... Thanks!... The 'enterprise policy' installed seemd the same.

Now as I tried to clean everything sem I made a mistake as currently I simply could not use the connector. Extension tells me thazt I have no connector while it's installed. I tried to remove and reinstall but nothing. I cleared everything about htis extension and removed the connector. Then I tried to install the connector and the extension from the store but nothing:( I'm killed it:)

If I check the /ect/opt;chromium... native-messaging-host dir those are empty and could not get it's content again.

As I'm not have more time for now I need to leave the whole process but as I told after I installed it based  on the wiki as an enterprise extension the result was the same:(

Sorry for leaving now:( (and for my English too:))

**Comment by nE0sIghT** [comment] 2017-03-21 11:20
> If I check the /ect/opt;chromium... native-messaging-host dir those are empty and could not get it's content again.

Just reinstall distro's chrome-gnome-shell package.

**Comment by ebola-dc** [comment] 2017-03-27 12:55
Hello!

After all I tryed to restore all of the functions before. I had lot of problem with connector itself (neither versiion of distribution or your PPA not made new host files on a computer what ever destructed from this aspect but I copied from anouther sterile device) but at the end I just sucessfully restored everything.

So currently I have 3 devices enablend extension from latest source code as you can see on the following screenshot:

![image](https://cloud.githubusercontent.com/assets/25765137/24357147/fb233202-12fc-11e7-8bb7-fa1f1ed3544d.png)
The problem is what I wrote before. With this new and corrected Chrome extension the result is the same. Half hours ago I got simply uninstalled Gnome extensions not just disabled ones. After 2 hours sleep of my device and after the wake up I simply lost almost all of my Gnome extensions.

Sorry to say but I need to absolutly finally report taht the problem is still available sot the issue is not solved yet:(

Thanks for your continous efforts!

**Comment by ebola-dc** [comment] 2017-03-30 08:08
Hello!

I know that this is not a strong opinion but maybe could help.

With this 'fresh' version directly from source code the problem is lot rarer. Not solved as I still got 'disabling' and 'uninstalling' twice while I use this last 'beta' but obviously rarer then before.

Hope taht this information could also be helpful.

Thanks again!

**Comment by nE0sIghT** [comment] 2017-03-30 08:18
@ebola-dc 

Please try this:

1. Clean ```build``` directory in source code
2. Edit ```extension/include/sync.js``` file: change line ```const SYNC_QUEUE_TIMEOUT = 3000;``` to ```const SYNC_QUEUE_TIMEOUT = 10000;```
3. Rebuild extension and reload to your devices

**Comment by ebola-dc** [comment] 2017-04-03 09:02
Thank you!

Something such change was my first idea in my other thread. I did it, and installed. Let's see the result in the next days.

Thanks again!

**Closed** 2017-04-16 17:40 UTC

**Comment by ebola-dc** [comment] 2017-04-19 14:22
OK!

Just to inform you it seems that the longer timeout and the other changes made good result as in the last 2 weeks I did not have the original problem. Please make longer the timeout value in your official release also.

Thanks for it!

**Comment by nE0sIghT** [comment] 2017-04-19 14:25
@ebola-dc I increased timeout to 7 secs.

**Comment by ckrzen** [comment] 2017-05-11 16:10
I had to disable the:

Synchronize GNOME Shell extensions list:
If enabled, your GNOME Shell extensions list will be synchronized with your Google account.

option due to having my .config/google-chrome dir copied from my main system to alt workstation for ease of install.

Not sure if this causes problems like one-way sync, but -- just letting you know.

**Comment by bulletmark** [comment] 2018-05-23 03:04
I'm on Arch Linux with google-chrome 66.0.3359.181-1 and chrome-gnome-shell 10.1-1 and my extensions frequently get disabled due to this issue, both on my notebook and my PC. Clearly this issue is not fixed.
