### ISSUE TITLE
No notification of installed extension update

### ISSUE THREAD

**Issue by eda2z** [nE0sIghT/chrome-gnome-shell-mirror#36] opened 2017-02-21 14:47 UTC
Since the gnome shell extension website has changed where their "icons" are displayed I am no longer getting notifications of updates when I start up my browser.  The latest example is OpenWeather (openweather-extension@jenslody.de) which just occurred today.  I have also noticed it happening on "Dash to Panel" (dash-to-panel@jderose9.github.com).  I am running on Arch linux in chrome (google-chrome 56.0.2924.87-1) with chrome-gnome-shell-git 8.1.r2.g2b48063-1.

This may not be a bug but rather some option in gnome and/or chrome that is not set correctly.  Is there anything like that which I should check?  Thanks.

**Comment by nE0sIghT** [comment] 2017-02-21 14:55
1. Please post here content of files ```~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/metadata.json``` and ```~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json```.

2. Edit ```/usr/bin/chrome-gnome-shell``` file as root user and change ```DEBUG_ENABLED = False``` to ```DEBUG_ENABLED = True```. 
Run Chrome from comand line, go to browser extension settings. Disable update check and enable it.
Post here Chrome output.

**Comment by eda2z** [comment] 2017-02-21 15:29
Attached are the files you requested.  I had to rename the .json files since that file type was not allowed, and chrome.txt contains the debug output.  However, before you start spending a lot of time looking for a bug which may not exist (I'm a retired software developer so I know the feeling) wait for a follow on message later today.  The reason why is that when I toggled the Update Check switch back to Yes then a Notification appeared.  I then exited chrome, started it from the Activity menu, toddled the switch again and a notification appeared.  I decreased the time down to 3 hrs. and I will try again later to see if it is detected.

[openweather.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/790552/openweather.txt)
[dashtopanel.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/790553/dashtopanel.txt)
[chrome.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/790554/chrome.txt)

**Comment by nE0sIghT** [comment] 2017-02-21 15:38
I think that I really break auto update check since I do not remember when I get one last time.
But indeed, manual timer refresh works well

**Comment by eda2z** [comment] 2017-02-21 19:38
I launched gnome after the "Update check period" expired and did not receive a notification.  If I toggled the Update Check switch then I did get a notification.  Also, the Last Check and Next Check times were both updated.  Anything else I can provide?

**Comment by nE0sIghT** [comment] 2017-02-21 19:52
No, thanks. I was able to reproduce this.

**Comment by nE0sIghT** [comment] 2017-02-21 20:54
This is fixed in master and will be available in next browser extension release.
Thanks for report!

**Closed** 2017-02-21 21:00 UTC
