### ISSUE TITLE
Segfault on Fedora 25

### ISSUE THREAD

**Issue by dbasinge** [nE0sIghT/chrome-gnome-shell-mirror#30] opened 2017-02-08 14:20 UTC
Keep seeing the same segfault on Fedora 25, have installed chrome-gnome-shell from dnf copr as suggested on web page.

[ 2592.067169] chrome-gnome-sh[8444]: segfault at 0 ip 00007f43f67cb830 sp 00007ffcabfd0a28 error 4 in libgio-2.0.so.0.5000.2[7f43f672b000+18a000]
[39119.372537] chrome-gnome-sh[11061]: segfault at 0 ip 00007f0e70c2a830 sp 00007ffc4957e868 error 4 in libgio-2.0.so.0.5000.2[7f0e70b8a000+18a000]
[39284.403518] chrome-gnome-sh[26968]: segfault at 0 ip 00007f216b3ff830 sp 00007ffda9884a68 error 4 in libgio-2.0.so.0.5000.2[7f216b35f000+18a000]
[39325.584428] chrome-gnome-sh[28993]: segfault at 0 ip 00007fa1e5fa5830 sp 00007ffea7751198 error 4 in libgio-2.0.so.0.5000.2[7fa1e5f05000+18a000]
[39532.482122] chrome-gnome-sh[29474]: segfault at 0 ip 00007f91f33b1830 sp 00007fff1e702b88 error 4 in libgio-2.0.so.0.5000.2[7f91f3311000+18a000]
[39541.855954] chrome-gnome-sh[30260]: segfault at 0 ip 00007f255ab51830 sp 00007ffe3f4eb838 error 4 in libgio-2.0.so.0.5000.2[7f255aab1000+18a000]

**Comment by nE0sIghT** [comment] 2017-02-08 14:31
Duplicate of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/27
Already fixed in master. Will be available in version 8.1.

You can ask Fedora's package maintainer to apply patch from git master branch.

**Closed by nE0sIghT** 2017-02-08 14:31 UTC
