### ISSUE TITLE
https://extensions.gnome.org/ shows no_gnome_shell

### ISSUE THREAD

**Issue by madguy000** [nE0sIghT/chrome-gnome-shell-mirror#76] opened 2017-08-20 06:15 UTC
I have installed the mozilla firefox plugin and followed the instructions to install on https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation. Despite this, I see the error on the Gnome extension website. My objective is to add a few add-ons for Gnome shell.

I have Ubuntu 17.04 with no customizations.

![no gnome shell](https://user-images.githubusercontent.com/31175971/29492550-741549dc-856e-11e7-9c8d-333a88d17cac.png)

**Comment by nE0sIghT** [comment] 2017-08-20 08:33
You do not have GNOME Shell installed or running.
GNOME Shell integration works only with GNOME Shell.

Duplicate of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/35

**Closed by nE0sIghT** 2017-08-20 08:33 UTC
