### ISSUE TITLE
High CPU usage and crash with Firefox on Ubuntu 16.04

### ISSUE THREAD

**Issue by rrthomas** [nE0sIghT/chrome-gnome-shell-mirror#49] opened 2017-03-14 13:36 UTC
First, thanks very much for your hard work on browser integration for GNOME extensions!

I see that Firefox 52 support is available. Since Firefox 52 has now landed in Ubuntu, please could you make a release?

Also, I see that version 8.2 was only released in your PPA for trusty, for some reason, and not for xenial &c.

I just switched back to Firefox after some time using Chromium, and when I installed chrome-gnome-shell, found that suddenly Firefox crashed on exit etc. That's not surprising, as I'm using only 8.1.

**Comment by nE0sIghT** [comment] 2017-03-14 14:36
Are you using Ubuntu 16.10?

**Comment by rrthomas** [comment] 2017-03-14 14:40
I'm using 16.04.

**Comment by rrthomas** [comment] 2017-03-14 15:18
I'm using version 8.1, from your PPA for 16.04. Commit 2f4007a mentions updating compatibility to Firefox 52, and this commit is after release 8.

**Comment by nE0sIghT** [comment] 2017-03-14 17:04
Version 8.1 should not crash.
Do you have HTitle addon installed?

**Comment by rrthomas** [comment] 2017-03-14 17:14
No, I don't have HTitle. The crash is when Firefox shuts down: it consumes 100% CPU for about 30 seconds, then gives a crash dialog. The code that is taking too long is in native messaging.

I'm sorry, I have not given much information up to now because I thought that a Firefox 52-compatible version had not been released. I'm busy with Firefox right now, but when I finish, I will do some proper tests and add better information to this bug report.

**Comment by nE0sIghT** [comment] 2017-03-14 17:21
Please list your installed Firefox addons.
It looks similar to [this HTitle issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1337799)

**Comment by rrthomas** [comment] 2017-03-14 17:23
Sure, I have the following: 404 Bookmarks, Add-on Compatibility Reporter, Google search link fix, Greasemonkey, NoSquint Plus, Open With, Stylish, Tab Mix Plus, uBlock Origin, Wayback Machine (plus GNOME Shell Integration, currently disabled).

**Comment by nE0sIghT** [comment] 2017-03-15 02:36
I can not reproduce this.
Please try to enable GNOME Shell integration and disable your extensions one by one to determine which of them is incompatible with WebExtensions Native messaging.

**Comment by rrthomas** [comment] 2017-03-15 09:28
I disabled all the extensions except GNOME Shell Integration, and the error persists. Here is a complete log of terminal output:

    1489568070598	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
    1489568070605	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.
    1489568070605	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.
    JavaScript error: chrome://mozapps/content/extensions/extensions.js, line 737: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIControllers.removeController]
    [Parent 2145] WARNING: waitpid failed pid:2219 errno:10: file /build/firefox-ZQQBpC/firefox-52.0+build2/ipc/chromium/src/base/process_util_posix.cc, line 268
    WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:close:414","resource://gre/modules/ExtensionCommon.jsm:unload:362","resource://gre/modules/ExtensionParent.jsm:unload:292","resource://gre/modules/ExtensionParent.jsm:shutdown:284","resource://gre/modules/ExtensionParent.jsm:shutdown:355","resource://gre/modules/ExtensionParent.jsm:shutdownExtension:386","resource://gre/modules/Extension.jsm:shutdown:871","resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/WebExtensionBootstrap.js:shutdown:34","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.callBootstrapMethod:4968","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.startup/<.observe:2924","chrome://mozapps/content/extensions/extensions.js:gViewController.commands.cmd_restartApp.doCommand:932","chrome://mozapps/content/extensions/extensions.xml:restart:1522","about:addons:oncommand:1"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]}] Barrier: profile-before-change

**Comment by rrthomas** [comment] 2017-03-15 09:31
Also, the problem continues for at least one restart of Firefox even after I disable the GNOME Shell Integration extension (so that I have no extensions enabled).

I tried this once, and Firefox started working normally again on the second restart.

I then re-enabled just GNOME Shell Integration, and the problem returned.

After that, I disabled GNOME Shell Integration (so again, no extensions enabled), and restarted Firefox 3 or 4 times, and it still crashed each time.

I then re-enabled a single other extension (Add-on Compatibility Reporter), and after that, Firefox shutdown normally each time.

Finally, I re-enabled all the rest of my extensions (so now everything is enabled except GNOME Shell Integration) and it is all working.

**Comment by rrthomas** [comment] 2017-03-15 09:32
The crash always seems to have the same cause, that is, it is not really a crash, but a timeout caused by waiting too long, with the same error as I pasted above.

**Comment by nE0sIghT** [comment] 2017-03-15 12:51
Could you try Chromium (or Opera) and Firefox with clean profile?

**Comment by rrthomas** [comment] 2017-03-15 12:52
I have been using Chromium too (also installed from Ubuntu 16.04) without problems. I will test Firefox with a clean test profile shortly.

**Comment by rrthomas** [comment] 2017-03-15 12:56
Installing GNOME Shell Integration (by going to extensions.gnome.org) into a clean Firefox profile gives the same crash as I reported above.

**Comment by nE0sIghT** [comment] 2017-03-15 17:10
Do you using 64 bit distro?

**Comment by rrthomas** [comment] 2017-03-15 17:24
Yes.

-- 
http://rrt.sc3d.org

**Comment by nE0sIghT** [comment] 2017-03-15 18:34
Please edit "/usr/bin/chrome-gnome-shell" and change "DEBUG_ENABLED = False" to "DEBUG_ENABLED = True".
Then run Firefox with "firefox -jsconsole" and close it.
Post Browser console output here.

**Comment by nE0sIghT** [comment] 2017-03-15 18:58
For easy collecting logs please use [this connector](https://git.gnome.org/browse/chrome-gnome-shell/tree/connector/chrome-gnome-shell.py?h=debug/issue/49) - place it to /usr/bin overriding chrome-gnome-shell and change shebang at 1st line to correct one for your distro.
Run Firefox, get crash and attach "/tmp/cgs*" files to this bugreport.

**Comment by rrthomas** [comment] 2017-03-16 09:39
Files attached. I ran with `-jsconsole`, and noted that your special connector already had `DEBUG_ENABLED = True`.

Log files attached.

[cgs-6752-6817.stderr.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/847253/cgs-6752-6817.stderr.txt)
[cgs-6752-6818.stderr.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/847255/cgs-6752-6818.stderr.txt)
[cgs-6752-7516.stderr.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/847254/cgs-6752-7516.stderr.txt)
[cgs-6825-6826.stderr.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/847256/cgs-6825-6826.stderr.txt)

**Comment by nE0sIghT** [comment] 2017-03-16 09:49
According to logs there are no errors in connector and it's all instances quit normally.
It's for sure a bug in Firefox and it is same as with HTitle addon.

I will create new issue in Firefox bugzilla later today.

For now I do not know how to dig this deeper without reproducing this since clean 16.04 VirtualBox machine is unaffected.

**Comment by rrthomas** [comment] 2017-03-16 09:53
Thanks very much for your efforts.

**Comment by rrthomas** [comment] 2017-03-16 10:05
One other piece of information: above, I noted that the crashes continued after I disabled the Chrome Gnome Shell Extension. I noticed similarly just now that one of my extensions (in this case, NoSquint Plus), was not active, despite being enabled. I had to disable and re-enable it to get it to work. This also stopped the crashes which were continuing although Chrome Gnome Shell Extension was disabled (along with messages about the connector). So it seems that for some reason the state of extensions becomes confused, and their actual status (enabled/disabled) gets out of sync with the status in the Add-ons dialog, even after a restart.

**Comment by nE0sIghT** [comment] 2017-03-23 08:37
Reported this to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1349874

**Comment by rrthomas** [comment] 2017-03-23 10:31
Thanks very much for your work on this issue.

**Comment by nobeh** [comment] 2017-04-10 19:31
Having the same issue on FF 53.0 Ubuntu 16.10:

```
Apr 10 21:16:51 nobeh-bno firefox.desktop[32079]: ###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
Apr 10 21:17:01 nobeh-bno firefox.desktop[32079]: WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:close:414","resource://gre/modules/ExtensionCommon.jsm:unload:362","resource://gre/modules/ExtensionParent.jsm:unload:316","resource://gre/modules/ExtensionParent.jsm:shutdown:308","resource://gre/modules/ExtensionParent.jsm:shutdown:382","resource://gre/modules/ExtensionParent.jsm:shutdownExtension:464","resource://gre/modules/Extension.jsm:shutdown:936","resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/WebExtensionBootstrap.js:shutdown:33","resource://gre/modules/addons/XPIProvider.jsm:callBootstrapMethod:4903","resource://gre/modules/addons/XPIProvider.jsm:observe:2884"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource
Apr 10 21:17:01 nobeh-bno firefox.desktop[32079]: ://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]}] Barrier: profile-before-change
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: console.error:
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]:   Message: Error: SessionFile is closed
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]:   Stack:
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]:     write@resource://app/modules/sessionstore/SessionFile.jsm:315:29
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: write@resource://app/modules/sessionstore/SessionFile.jsm:76:12
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: _writeState@resource://app/modules/sessionstore/SessionSaver.jsm:265:12
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: _saveState@resource://app/modules/sessionstore/SessionSaver.jsm:236:12
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: _saveStateAsync@resource://app/modules/sessionstore/SessionSaver.jsm:249:5
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: runDelayed/this._timeoutID<@resource://app/modules/sessionstore/SessionSaver.jsm:147:40
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: setTimeout_timer@resource://gre/modules/Timer.jsm:30:5
Apr 10 21:17:05 nobeh-bno firefox.desktop[32079]: observe@resource://gre/modules/AsyncShutdown.jsm:550:9
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: FATAL ERROR: AsyncShutdown timeout in profile-before-change Conditions: [{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:close:414","resource://gre/modules/ExtensionCommon.jsm:unload:362","resource://gre/modules/ExtensionParent.jsm:unload:316","resource://gre/modules/ExtensionParent.jsm:shutdown:308","resource://gre/modules/ExtensionParent.jsm:shutdown:382","resource://gre/modules/ExtensionParent.jsm:shutdownExtension:464","resource://gre/modules/Extension.jsm:shutdown:936","resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/WebExtensionBootstrap.js:shutdown:33","resource://gre/modules/addons/XPIProvider.jsm:callBootstrapMethod:4903","resource://gre/modules/addons/XPIProvider.jsm:observe:2884"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:doCleanup:386","resource://gre/modules/
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]}] At least one completion condition failed to complete within a reasonable amount of time. Causing a crash to ensure that we do not leave the user with an unresponsive process draining resources.
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: #007[Parent 32079] ###!!! ABORT: file resource://gre/modules/NativeMessaging.jsm, line 386
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: [Parent 32079] ###!!! ABORT: file resource://gre/modules/NativeMessaging.jsm, line 386
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: ExceptionHandler::GenerateDump cloned child 23821
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: ExceptionHandler::SendContinueSignalToChild sent continue signal to child
Apr 10 21:17:52 nobeh-bno firefox.desktop[32079]: ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Apr 10 21:20:23 nobeh-bno firefox.desktop[32079]: Failed to open curl lib from binary, use libcurl.so instead
```

One guess that I am giving more weight is that we cannot have this plugin installed *both* for Chrome and FF; otherwise, when one is closing, it naturally leads to this issue? Does it make sense?

**Comment by nE0sIghT** [comment] 2017-04-10 19:35
> we cannot have this plugin installed both for Chrome and FF; otherwise, when one is closing, it naturally leads to this issue

It should work fine even in 4 browsers simultaneously.
You are just hit Firefox bug

**Comment by nE0sIghT** [comment] 2018-03-21 06:54
Looks like this issue was fixed in latest Firefox versions (somewhere after 54).
Is it still reproducible for you?

**Comment by rrthomas** [comment] 2018-03-21 10:54
Seems to be working fine now, thanks for checking!

**Comment by nE0sIghT** [comment] 2018-03-21 10:55
Thanks for feedback.
Closing then.

**Closed by nE0sIghT** 2018-03-21 10:55 UTC
