### ISSUE TITLE
Causes very high CPU usage

### ISSUE THREAD

**Issue by tliron** [nE0sIghT/chrome-gnome-shell-mirror#53] opened 2017-03-23 06:29 UTC
Ubuntu 16.04 AMD64, Firefox 52.0.1. Disabling the extension and restarting Firefox makes everything go back to normal. Note that the extension does work, it's just the super-high CPU usage that is a problem.

**Comment by nE0sIghT** [comment] 2017-03-23 06:31
Do you have HTitle addon installed?

**Comment by tliron** [comment] 2017-03-23 07:33
Yes. Is there a known conflict between them?

**Comment by nE0sIghT** [comment] 2017-03-23 07:35
> conflict between them?

Not between them, but between HTitle and ***any*** WebExtension with Native messaging

Duplicate of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/29
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1337799

**Comment by tliron** [comment] 2017-03-23 07:59
I removed HTitle but I'm getting the same issues -- removing this extension still solved the problem for me. Could there be another extension similar to HTitle that causes the same issue?

**Comment by nE0sIghT** [comment] 2017-03-23 08:03
Please show me list of your extensions.
Also try to run Firefox from terminal, get high CPU usage, close Firefox and collect it's output.

**Comment by tliron** [comment] 2017-03-23 08:09
Thanks! For now CPU usage seems normal. What should I expect to see in the output?

My extensions:

- Default Zoom Level
- DownloadThemAll!
- FlashGot
- GNOME Shell Integration
- GNOME Theme Tweak
- GNotifier
- Greasemonkey
- HTTP/2 and SPDY Indicator
- JSONView
- Messenger for Google Hangouts
- OneNote Web Clipper
- Reddit Enhancement Suite
- Save Button for Pinterest
- Steam Database
- Stylish
- UAControl
- uBlock Origin
- Ubuntu Modifications

**Comment by nE0sIghT** [comment] 2017-03-23 08:10
> Thanks! For now CPU usage seems normal.

So looks like your issue was with HTitle?

**Comment by tliron** [comment] 2017-03-23 08:13
No, sorry, I uninstalled this extension by mistake. :) Reinstalling it brought CPU back up again and I got these error messages in the console:
```
1490256619147	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1490256619151	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.
1490256619151	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.
1490256642384	addons.xpi	WARN	Exception running bootstrap method shutdown on aushelper@mozilla.org: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/emblemparade/.mozilla/firefox/q1p0ilyz.default/features/%7B29c7d987-930a-43cb-9bda-576550a41c7a%7D/aushelper@mozilla.org.xpi!/bootstrap.js :: shutdown :: line 196"  data: no] Stack trace: shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/emblemparade/.mozilla/firefox/q1p0ilyz.default/features/%7B29c7d987-930a-43cb-9bda-576550a41c7a%7D/aushelper@mozilla.org.xpi!/bootstrap.js:196 < this.XPIProvider.callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4968 < this.XPIProvider.startup/<.observe()@resource://gre/modules/addons/XPIProvider.jsm:2924


WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:close:414","resource://gre/modules/ExtensionCommon.jsm:unload:362","resource://gre/modules/ExtensionParent.jsm:unload:292","resource://gre/modules/ExtensionParent.jsm:shutdown:284","resource://gre/modules/ExtensionParent.jsm:shutdown:355","resource://gre/modules/ExtensionParent.jsm:shutdownExtension:386","resource://gre/modules/Extension.jsm:shutdown:871","resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/WebExtensionBootstrap.js:shutdown:34","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.callBootstrapMethod:4968","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.startup/<.observe:2924"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]}] Barrier: profile-before-change
console.error: 
  Message: Error: SessionFile is closed
  Stack:
    SessionFileInternal.write@resource://app/modules/sessionstore/SessionFile.jsm:315:29
this.SessionFile.write@resource://app/modules/sessionstore/SessionFile.jsm:76:12
SessionSaverInternal._writeState@resource://app/modules/sessionstore/SessionSaver.jsm:259:12
SessionSaverInternal._saveState@resource://app/modules/sessionstore/SessionSaver.jsm:230:12
SessionSaverInternal._saveStateAsync@resource://app/modules/sessionstore/SessionSaver.jsm:243:5
SessionSaverInternal.runDelayed/this._timeoutID<@resource://app/modules/sessionstore/SessionSaver.jsm:147:40
setTimeout_timer@resource://gre/modules/Timer.jsm:30:5
Spinner.prototype.observe@resource://gre/modules/AsyncShutdown.jsm:550:9
FATAL ERROR: AsyncShutdown timeout in profile-before-change Conditions: [{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:sendMessage/<:429"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:close:414","resource://gre/modules/ExtensionCommon.jsm:unload:362","resource://gre/modules/ExtensionParent.jsm:unload:292","resource://gre/modules/ExtensionParent.jsm:shutdown:284","resource://gre/modules/ExtensionParent.jsm:shutdown:355","resource://gre/modules/ExtensionParent.jsm:shutdownExtension:386","resource://gre/modules/Extension.jsm:shutdown:871","resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/WebExtensionBootstrap.js:shutdown:34","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.callBootstrapMethod:4968","resource://gre/modules/addons/XPIProvider.jsm:this.XPIProvider.startup/<.observe:2924"]},{"name":"Native Messaging: Wait for application org.gnome.chrome_gnome_shell to exit","state":"(none)","filename":"resource://gre/modules/NativeMessaging.jsm","lineNumber":386,"stack":["resource://gre/modules/NativeMessaging.jsm:_cleanup/doCleanup:386","resource://gre/modules/NativeMessaging.jsm:_cleanup:398","resource://gre/modules/NativeMessaging.jsm:_startRead/this.readPromise<:285"]}] At least one completion condition failed to complete within a reasonable amount of time. Causing a crash to ensure that we do not leave the user with an unresponsive process draining resources.
[5031] ###!!! ABORT: file resource://gre/modules/NativeMessaging.jsm, line 386
[5031] ###!!! ABORT: file resource://gre/modules/NativeMessaging.jsm, line 386
ExceptionHandler::GenerateDump cloned child 5447
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```

**Comment by nE0sIghT** [comment] 2017-03-23 08:15
Please try to reproduce this in clean profile with GNOME Shell integration extension only.

**Comment by nE0sIghT** [comment] 2017-03-23 08:37
Reported this to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1349874

**Comment by tliron** [comment] 2017-03-24 08:08
Incredibly, I think the culprit might be [GNOME Theme Tweak](https://github.com/gnome-integration-team/firefox-gnome). I've been running this extension for 20 minutes with that one disabled and CPU usage is normal. What do you think could be causing this conflict with that extension?

**Comment by nE0sIghT** [comment] 2017-03-24 08:14
@seleznev

Any thoughts?

**Comment by tliron** [comment] 2017-03-24 09:13
Restarting my Firefox (same configuration) made the problem return. Well, let me try for a few days with different extensions and see if I can isolate it.

**Comment by MeisterP** [comment] 2017-03-28 14:22
For me it's the `GNotifier` extension that triggers the issue.

**Comment by nE0sIghT** [comment] 2017-04-01 06:33
@MeisterP 

I can not reproduce this with GNotifier

**Comment by Gwend4l** [comment] 2017-04-14 07:24
I also encounter the high CPU usage problem, although I have not yet identified if it was because of another conflicting extension.

**Comment by nE0sIghT** [comment] 2017-04-14 08:33
@Gwend4l 
I think it would be more usefull if you will ping Mozilla team at [bug 1342850](https://bugzilla.mozilla.org/show_bug.cgi?id=1342850).

**Comment by honza-kasik** [comment] 2017-06-10 06:22
If you are affected by Firefox [bug 1342850](https://bugzilla.mozilla.org/show_bug.cgi?id=1342850), vote for this bug's page at Mozilla's bugzilla. See [article about voting](https://bugzilla.mozilla.org/page.cgi?id=voting.html) for more details.

We have to indicate that fixing that bug is important for us. You can even sign in with your GitHub account, so go for it!

**Comment by Gwend4l** [comment] 2017-06-10 07:07
Voted! thanks for suggesting this

**Comment by nE0sIghT** [comment] 2018-03-21 06:54
Looks like this issue was fixed in latest Firefox versions (somewhere after 54).
Is it still reproducible for you?

**Comment by nE0sIghT** [comment] 2018-03-21 10:57
Reopen if you still reproducing issue.

**Closed by nE0sIghT** 2018-03-21 10:57 UTC
