### ISSUE TITLE
When clicking on the on/off button of the extension website nothing happens

### ISSUE THREAD

**Issue by fteppe** [nE0sIghT/chrome-gnome-shell-mirror#89] opened 2018-03-19 12:45 UTC
Hello,
I' don't know if it's the extension's fault. But when I try to download an extension on the website, and I click on the switch, in turns to "on" but it doesn't download the extension. And if I refresh the page it goes back to "off".

The same thing happens with the firefox version. I am using Ubuntu 17.10 in virtualBox

**Comment by nE0sIghT** [comment] 2018-03-19 15:11
Do you see black overlay with question "Would you want to install.." after clicking switch?
Please open browser console (F12 -> Console), click switch and post console output here.
Which browsers did you test?

**Comment by fteppe** [comment] 2018-03-19 15:29
![screen gnome](https://user-images.githubusercontent.com/16321628/37605018-9a2cdeb2-2b92-11e8-9a5c-5b9320c2abb9.jpg)

So I tried on firefox and chrome and both give similar results, there is no overlay when I click, it just seems to do nothing.

**Comment by nE0sIghT** [comment] 2018-03-19 16:53
You posted screenshot of "Network" tab.
Please select "Console" tab, click switch and take screenshot.

**Comment by fteppe** [comment] 2018-03-19 17:10
![screenshot from 2018-03-19 18-09-00](https://user-images.githubusercontent.com/16321628/37610745-b66cc82c-2ba0-11e8-9022-8fb38f9760fe.png)
My bad, all it seems to be saying after a while is uncaught timeout exception.

I use the internet through a firewall, it is set properly in Firefox but could it cause an issue?

**Comment by nE0sIghT** [comment] 2018-03-19 17:13
Does exception occurs after you clicked switch? Or it appears after loading page?

**Comment by fteppe** [comment] 2018-03-19 17:22
A few seconds after I clicked the switch

**Comment by nE0sIghT** [comment] 2018-03-19 17:24
Which native connector version do you using (chrome-gnome-shell package in your distro)?

**Comment by fteppe** [comment] 2018-03-20 09:08
All I can see is the verion in apt (9-0ubuntu1), since chrome-gnome-shell -v or --version doesn't exist and chrome-gnome-shell --help only gives options -h, --help and --help-all

**Comment by nE0sIghT** [comment] 2018-03-20 10:54
Please show output of
```gsettings list-recursively org.gnome.system.proxy```

**Comment by fteppe** [comment] 2018-03-20 11:05
org.gnome.system.proxy use-same-proxy true
org.gnome.system.proxy mode 'auto'
org.gnome.system.proxy autoconfig-url 'http://wpad.manh.fr.sopra/wpad-gal.dat'
org.gnome.system.proxy ignore-hosts ['localhost', '127.0.0.0/8', '::1']
org.gnome.system.proxy.ftp host ''
org.gnome.system.proxy.ftp port 0
org.gnome.system.proxy.socks host ''
org.gnome.system.proxy.socks port 0
org.gnome.system.proxy.http host ''
org.gnome.system.proxy.http port 8080
org.gnome.system.proxy.http use-authentication false
org.gnome.system.proxy.http authentication-password ''
org.gnome.system.proxy.http authentication-user ''
org.gnome.system.proxy.http enabled false
org.gnome.system.proxy.https host ''
org.gnome.system.proxy.https port 0

it seems it doesn't have the password and username I use for the proxy, could it be the issue?

**Comment by nE0sIghT** [comment] 2018-03-20 11:10
There can be 2 issues:
1. You are using proxy autoconfig URL (PAC). One user claimed this is not works in GNOME Shell [[1]](https://bugzilla.gnome.org/show_bug.cgi?id=759775).
2. Yes, missed username and password may be the cause.

Actually, download of extensions is processed in GNOME Shell, not in the browser or integration extension. Therefore your GNOME Shell should be properly configured to use proxy.

[1] https://bugzilla.gnome.org/show_bug.cgi?id=759775

**Comment by fteppe** [comment] 2018-03-20 12:52
Ok I configured it to use the proxy and it is now working, thanks.

It seems that I needed to set the proxy on manual and input all the configuration. But it doesn't seem that the username, pwd were necessary.

**Comment by nE0sIghT** [comment] 2018-03-20 18:53
Glad to hear it works for you. Closing then.

**Closed by nE0sIghT** 2018-03-20 18:53 UTC
