### ISSUE TITLE
firefox crash

### ISSUE THREAD

**Issue by MrReSc** [nE0sIghT/chrome-gnome-shell-mirror#54] opened 2017-04-01 05:47 UTC
Hello

I installed the chrome-gnome-shell package from Fedora repos. Basically it is working. But if i close firefox and reopen it then the following fault occurs:

![bildschirmfoto vom 2017-04-01 07-15-32](https://cloud.githubusercontent.com/assets/24952268/24575661/edbf2bee-16ac-11e7-9709-5e37e5f05285.png)

After a couple minutes of waiting the crash report window from firefox appears. If i run `killall firefox` before the crash report appears, I'm able to start firefox again.

You can find the crash report here: [https://paste.fedoraproject.org/paste/QH9kaJr9e5iXNWrjUYlirV5M1UNdIGYhyRLivL9gydE=/raw](url)

As soon as i remove chrome-gnome-shell, everything is working normal.

My System:
Fedora 25
chrome-gnome-shell.noarch 8.2-1.fc25 
firefox.x86_64 52.0-7.fc25 
XPS13 4.10.5-200.fc25.x86_64

**Comment by nE0sIghT** [comment] 2017-04-01 05:57
This is duplicate of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/53 or of https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/49
Basically: if you have HTitle addon installed - remove it.
If you have GNotifier addon installed - remove it.

If it is still issue and you do not have any other addons - you are hit [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1342850) - you can ask Mozilla's team to fix it as soon as possible.

**Closed by nE0sIghT** 2017-04-01 05:57 UTC
